name: 02 - Building Blocks
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  push:
  workflow_dispatch:
jobs:
  say-hello-version:
    runs-on: self-hosted
    steps:
      - run: echo hello
      - run: echo hello-2
  
  say-2hello-version:
    runs-on: self-hosted
    steps:
      - run: echo i am going to fail
      - run: exit 0
      - run: echo after failed exit
